import pandas as pd

def train_ea(timetable: pd.DataFrame, restrictions: list[dict]) -> pd.DataFrame:
    """Network-level EA generated by the union of active restrictions.
    Each restriction: section,direction,length_km,psr_kph,caution_kph.
    Synthetic running-time approximation; replace with real timetable/path model.
    """
    rows=[]
    for _,tr in timetable.iterrows():
        ea=0.0
        for s in restrictions:
            if str(tr.section)!=str(s["section"]): continue
            sd=str(s.get("direction","BOTH")).upper(); td=str(tr.direction).upper()
            if sd!="BOTH" and td!=sd: continue
            base=min(float(tr.max_speed_kph),float(s["psr_kph"]))
            restricted=min(base,float(s["caution_kph"]))
            if restricted<base:
                ea += 60.0*float(s["length_km"])*(1/restricted-1/base)
        rows.append({"train_id":tr.train_id,"train_class":tr.train_class,"ea_min":ea,"weight":float(tr.get("weight",1.0))})
    out=pd.DataFrame(rows)
    if not out.empty: out["weighted_ea_min"]=out.ea_min*out.weight
    return out
